return PlaceObj('ModDef', {
	'title', "Tremualin's Library",
	'description', "I got tired of writing the same code and fixing the same bugs in all my mods, so I decided to make a shared library with all my code, and tests.\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588520023]Steam[/url]\n[url=https://mods.paradoxplaza.com/mods/29864/Any]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods/tree/main/Tremualin's%20Library]Github[/url]",
	'image', "Icon.png",
	'last_changes', "Added a function to determine if a Medical Spire or Hospital is present in the Dome",
	'id', "Tremualin_Library",
	'steam_id', "2588520023",
	'pops_desktop_uuid', "528d9c7d-a649-4912-8e89-04d7e567dd3c",
	'pops_any_uuid', "c6935ae7-5714-41c2-a503-54a162e3d0fb",
	'author', "Tremualin",
	'version_major', 1,
	'version_minor', 5,
	'version', 42,
	'lua_revision', 1007000,
	'saved_with_revision', 1008107,
	'code', {
		"Code/Common.lua",
		"Code/CommonUI.lua",
		"Code/Numbers.lua",
		"Code/Labels.lua",
		"Code/Fixes.lua",
	},
	'saved', 1633835554,
	'screenshot1', "PrintVisitDurations.jpg",
	'TagOther', true,
})