return PlaceObj('ModDef', {
	'title', "Improved Underpowered Techs",
	'description', "These technologies felt slightly under-powered to me, to the point where I often skipped them, so I buffed them a little.\n\n[list]\n    [*]Fuel Compression: Rocket Rare Metal Export capacity increased by 10.\n    [*]Smart Homes: All new buildings have a chance of satisfying Luxury, Drinking, Gaming and/or Exercise. The higher the comfort level, the higher the chance.\n    [*]Adapted Probes: Immediately gain 3 Probes\n[/list]\n\nThere are still more technologies which feel under powered but I haven't implemented the improvements yet:\n\nMartian Festivals is a late-game tech which grants +10 comfort for Decorations; not only you don't need it in the late game, the bonus isn't worth it. I shall make them grant satisfaction to tourists, if possible.\n\nResilient Architecture is a late-game tech which reduces the maintenance of out of dome buildings...which are usually maintenance free thanks to scrubbers. I'm not sure yet what I'll do with this technology, if I'll do anything. \n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.jpg",
	'last_changes', "Initial version",
	'id', "Tremualin_Improved_Underpowered_Techs",
	'steam_id', "2596427187",
	'pops_desktop_uuid', "107a9f89-30b9-4c8b-aec8-06c148186e89",
	'pops_any_uuid', "db45d922-d82b-4d33-90a9-482eedd756be",
	'author', "Tremualin",
	'version_major', 1,
	'version', 6,
	'lua_revision', 1007000,
	'saved_with_revision', 1007783,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1631083470,
	'screenshot1', "FuelCompression.png",
	'screenshot2', "SmartHome.jpg",
	'screenshot3', "Probes.png",
	'TagGameplay', true,
})