return PlaceObj('ModDef', {
	'title', "Improved Underpowered Techs",
	'description', "These technologies felt slightly under-powered to me, to the point where I often skipped them, so I buffed them a little.\n\n[list]\n    [*]Fuel Compression: Rocket Rare Metal Export capacity increased by 10.\n    [*]Smart Homes: All new buildings have a chance of satisfying Luxury, Drinking, Gaming and/or Exercise. The higher the comfort level, the higher the chance.\n    [*]Adapted Probes: Immediately gain 3 Probes\n    [*]Martian Festivals: Grants 2 satisfaction to tourists who visit Decorations\n    [*]Resilient Architecture: Salvaging now yields back the full cost of the the building\n[/list]\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.jpg",
	'last_changes', "Added Martian Festivals and Resilient Architecture",
	'id', "Tremualin_Improved_Underpowered_Techs",
	'steam_id', "2596427187",
	'pops_desktop_uuid', "107a9f89-30b9-4c8b-aec8-06c148186e89",
	'pops_any_uuid', "db45d922-d82b-4d33-90a9-482eedd756be",
	'author', "Tremualin",
	'version_major', 1,
	'version', 11,
	'lua_revision', 1007000,
	'saved_with_revision', 1007783,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1631424926,
	'screenshot1', "FuelCompression.png",
	'screenshot2', "SmartHome.jpg",
	'screenshot3', "Probes.png",
	'screenshot4', "MartianFestivals.png",
	'screenshot5', "ResilientArchitecture.png",
	'TagGameplay', true,
})