-- Add some helpful entries in the encyclopedia
local function AddEntriesToEncyclopedia()
    PlaceObj('EncyclopediaArticle', {
        SortKey = 10000,
        category_id = "Tremualin",
        group = "Tremualin",
        id = "Seasons of Mars - Introduction",
        text = table.concat({
            Untranslated("<white>Seasons of Mars</white> extends <em>Surviving Mars</em> with new seasonal effects and game mechanics."),
            Untranslated("<em>Vegetation</em> will change colors as <white>Seasons</white> change (requires Green Planet)"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> will vary across <white>Seasons</white> and <white>Latitudes</white>"),
            Untranslated("<em>Solar Irradiance</em> will modify the performance of <white>Farms, Solar Panels and Forestation Plants</white>."),
            Untranslated("<em>Solar Irradiance</em> can be disabled in mod options."),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> will vary across <white>Seasons</white> and <white>Latitudes</white>"),
            Untranslated("<em>Wind Speed</em> will modify the performance of <white>Wind Turbines.</white>"),
            Untranslated("<em>Wind Speed</em> can be disabled in mod options."),
            Untranslated("< newline >"),
            Untranslated("<em>Dust Storms</em> and <em>Cold Waves</em> will be longer and more frequent in certain <white>Seasons</white>."),
            Untranslated("<em>Northern colonies</em> will experience difference Seasons than <em>Southern colonies</em>."),
            Untranslated("Difficulty can be adjusted in mod options."),
            Untranslated("< newline >"),
            Untranslated("< newline >"),
            Untranslated("Will you Terraform your way out of the problem?"),
            Untranslated("Will you find refuge Below and Beyond instead?"),
            Untranslated("Or will you adapt and endure the Seasons?"),
        }, "< newline >"),
        title_id = "SeasonsofMarsIntroduction",
        title_text = Untranslated("Seasons of Mars - Introduction"),
    })

    PlaceObj('EncyclopediaArticle', {
        SortKey = 10001,
        category_id = "Tremualin",
        group = "Tremualin",
        id = "Seasons of Mars - Seasons",
        text = table.concat({
            Untranslated("Seasons on Mars are affected by both the planet's tilt and its distance from the Sun, leading to variations in length and intensity. The southern hemisphere has longer Autumns and Winters, but receives more sunlight during Summer and Spring, when Mars is closer to the Sun. < newline >"),
            Untranslated("Seasons duration is based on real Martian season duration for each hemisphere."),
            Untranslated("Seasons duration can be shortened in in ModOptions. Divided by 3 by default."),
            Untranslated("Disaster difficulty (duration, frequency) can be adjuster in ModOptions. Adjusted for (season duration)/3 by default. "),
            Untranslated("Remember to adjust difficulty accordingly if you change duration"),
            Untranslated("< newline >"),
            Untranslated("<white>Seasons on the Southern hemisphere</white><newline>"),
            Untranslated("<em>Spring</em>: <em>Dust Storms</em> become longer each sol. <em>Cold Waves</em> slowly normalize. <em>Solar Irradiance</em> grows."),
            Untranslated("<em>Summer</em>: <em>Dust Storms</em> appear faster each sol. <em>Cold Waves</em> normalize. <em>Solar Irradiance</em> grows to its highest point, then shrinks."),
            Untranslated("<em>Autumn</em>: <em>Cold Waves</em> become longer each sol. <em>Dust Storms</em> slowly normalize. <em>Solar Irradiance</em> shrinks."),
            Untranslated("<em>Winter</em>: <em>Cold Waves</em> appear faster each sol. <em>Dust Storms</em> are normal. <em>Solar Irradiance</em> shrinks to its lowest point then begins to grow."),
            Untranslated("< newline >"),
            Untranslated("<white>Seasons on the Northern hemisphere</white><newline>"),
            Untranslated("<em>Spring</em>: <em>Dust Storms</em> and <em>Cold Waves</em> normalize.. <em>Solar Irradiance</em> grows."),
            Untranslated("<em>Summer</em>: <em>Dust Storms</em> and <em>Cold Waves</em> normalize. <em>Solar Irradiance</em> grows to its highest point, then shrinks."),
            Untranslated("<em>Autumn</em>: <em>Dust Storms</em> and <em>Cold Waves</em> become longer each sol. <em>Solar Irradiance</em> shrinks."),
            Untranslated("<em>Winter</em>: <em>Dust Storms</em> and <em>Cold Waves</em> appear faster each sol. <em>Solar Irradiance</em> shrinks to its lowest point then begins to grow."),
        }, "< newline >"),
        title_id = "SeasonsofMarsSeasons",
        title_text = Untranslated("Seasons of Mars - Seasons"),
    })

    PlaceObj('EncyclopediaArticle', {
        SortKey = 10002,
        category_id = "Tremualin",
        group = "Tremualin",
        id = "Seasons of Mars - Solar Irradiance",
        text = table.concat({
            Untranslated("<em>Solar Irradiance</em> is the power per unit area (surface power density) received from the sun in the form of electromagnetic radiation. In simpler terms, it's how much solar power is shining down on a specific area at a given time. "),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> can increase or decrease the performance of <em>Farms</em> (half effect)"),
            Untranslated("<em>Solar Irradiance</em> can increase or decrease the performance of <em>Solar Panels</em> (full effect)"),
            Untranslated("<em>Solar Irradiance</em> can increase or decrease the performance of <em>Forestation Plants</em> (half effect)"),
            --Untranslated("<em>Solar Irradiance</em> can increase or decrease <em>Sanity</em> gained from <em>Sleep</em>"),
            Untranslated("Due to implementation issues, <em>Solar Irradiance</em> won't modify the performance of <em>Open Farms</em>"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> changes gradually with the seasons"),
            Untranslated("<em>Solar Irradiance</em> is stronger in Spring & Summer than in Autumn & Winter"),
            Untranslated("<em>Solar Irradiance</em> rate of change, min and max, are unique for each latitude"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> is stronger and more stable at the equator"),
            Untranslated("<em>Solar Irradiance</em> varies the most between seasons the farthest from the equator"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> bonuses are disabled at night"),
            Untranslated("<em>Solar Irradiance</em> bonuses stack with <em>The Artificial Sun</em>"),
            Untranslated("<em>Solar Irradiance</em> bonuses are disabled during <em>Dust Storms</em>"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> can be disabled in ModOptions"),
            Untranslated("< newline >"),
            Untranslated("<em>Solar Irradiance</em> math based is on graphs found on Reddit:"),
            Untranslated("https://www.reddit.com/r/Colonizemars/comments/5gj2st/i_simulated_solar_irradiance_on_mars_at_various/"),
            Untranslated("And then approximated to the closest sinusoidal functions"),
        }, "< newline >"),
        title_id = "SeasonsofMarsSolarIrradiance",
        title_text = Untranslated("Seasons of Mars - Solar Irradiance"),
    })

    PlaceObj('EncyclopediaArticle', {
        SortKey = 10002,
        category_id = "Tremualin",
        group = "Tremualin",
        id = "Seasons of Mars - Wind Speed",
        text = table.concat({
            Untranslated("<em>Wind Speed</em> describes how fast the air is moving past a certain point. There isn't enough information about wind speed patterns in Mars to accurately simulate wind speed, so this mod simulates it as a function of <em>Solar Irradiance</em>"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> can increase or decrease the performance of <em>Wind Turbines</em> (changes base value, applied after elevation)"),
            Untranslated("This means that a Large Wind Turbine (base production: 10) at 80% elevation (adjusted production: 18) and with a Wind Speed of -50% will end up producing 9 Power"),
            Untranslated("If upgraded (+33% production), it will end up producing 12 Power"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> changes gradually with the seasons"),
            Untranslated("<em>Wind Speed</em> is weaker in Spring & Summer than in in Autumn & Winter"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> is weaker and more stable at the equator"),
            Untranslated("<em>Wind Speed</em> varies the most between Seasons the farthest the colony is from the equator"),
            Untranslated("<em>Wind Speed</em> rate of change, min and max, are unique for each latitude"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> bonuses are disabled during <em>Dust Storms</em> (dust storm bonuses take over)"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> can be disabled in ModOptions"),
            Untranslated("< newline >"),
            Untranslated("<em>Wind Speed</em> is equal to negative two thirds of <em>Solar Irradiance</em>"),
            Untranslated("This means that if Solar Irradiance is 90%, then Wind Speed is -60%"),
            Untranslated("And if Solar Irradiance is -60%, then Wind Speed is +60%"),
        }, "< newline >"),
        title_id = "SeasonsofMarsWindSpeed",
        title_text = Untranslated("Seasons of Mars - Wind Speed"),
    })

    PlaceObj('EncyclopediaArticle', {
        SortKey = 10004,
        category_id = "Tremualin",
        group = "Tremualin",
        id = "Seasons of Mars - Colors",
        text = table.concat({
            Untranslated("<em>Vegetation</em> changes colors at the beginning of each new season (requires Green Planet)"),
            Untranslated("Colors only change at the beginning each new season (for performance reasons)"),
            Untranslated("< newline >"),
            Untranslated("If you have an extreme amount of vegetation and a slow CPU, you could experience some lag at the beginning of a new season"),
            Untranslated("If this becomes a problem, you can set ChangeColors to False in ModOptions and disable this option"),
        }, "< newline >"),
        title_id = "SeasonsofMarsVegetation",
        title_text = Untranslated("Seasons of Mars - Colors"),
    })
end
OnMsg.ClassesPostprocess = AddEntriesToEncyclopedia
