return PlaceObj('ModDef', {
	'title', "Advanced Bed and Breakfast",
	'description', "This mod tries to make B&B a bit less tedious to play with, by saving you clicks. It also includes an optional toggle that can help if your game sometimes freezes (not guaranteed to solve all freezes).\n\n[h1]Asteroid Mining[/h1]\n[b]New Asteroid Lander Button: Refab All[/b]. Refabs all buildings in the Asteroid. Use it when leaving the Asteroid for good instead of manually clicking over every single building. Cannot be used on Mars. As usual, you have a few seconds to cancel. \n\n[b]New Landing Pad: Asteroid Lander Pad[/b]. Asteroid Landers who return to Mars will automatically land on these landing pads, if available (you can still land the Lander manually if there are no pads available). Regular Rockets will still be able to use the Asteroid Lander Pads in case of an emergency. Note: I recommend you make one Asteroid Landing Pad for each Asteroid Lander you have, otherwise they'll wait in orbit. Landers won't use them if arriving from Earth. \n\n[b]New Toggle Button: To Mars And Back[/b]. Landers with this on will automatically transport resources to Mars when the lander is close to max capacity, refuel, come back to the last visited Asteroid, land in the same spot, and then repeat the process until canceled. Make sure to select the the resources you want before or after clicking the button and that there's enough fuel on Mars for the Lander to come back. Requires at least one free Asteroid Lander Pad on Mars (you can still land the Lander manually and it will then come back to Mars).  \nNote: If there's an ongoing dust storm, the lander will wait for the dust storm to be over before taking off. If the lander was already on route to Mars when the Dust Storm begins, it might land anyway, but it won't be able to return to the Asteroid until the Dust Storms ends. If you want to be 100% sure your Asteroid will not be drone-less during a Dust Storm, leave an RC Commander in the Asteroid or pause To Mars and Back when receiving a Dust Storm warning.\nNote: you can edit the payload in Mars (repair supplies) and the mod will bring it back.\n\n[b]Solar Energy Lander (Upgrade)[/b]: Asteroid Landers will be Solar Powered while in Space, thus removing fuel costs when moving to other Asteroids or back to Mars. Landers will still need fuel when departing from Mars. If To Mars and Back is selected and this upgrade is active, the Lander won't take any fuel back to the Asteroid. Costs 35 Exotics.\n\n[b]Multipurpose Upgrade Storage (Upgrade)[/b]: the Asteroid Lander will store the most common asteroid mining building upgrades on a special compartment, which means buildings built on Asteroids will be fully upgraded for free. You won't get the upgrade resources back when dismantling the buildings, however. Costs 70 Exotics.\n\n[h1]Underground[/h1]\n[b]Rubble Be Gone![/b]: You no longer need to click on cave in rubble to clear it. It spawns marked for removal. You still need to manually clear those giant collapsed tunnels.\n\n[b]Elevator Extenders[/b]: Drone Hub Extenders can now be connected to the Elevator. \n\n[b]Buried Wonder Chooser[/b]: you can choose which buried wonders you'd like to find in the mod options. Requires a new game/restart. There will always be exactly 2 Buried Wonders on each game. If you choose only one, the other one will be random. If you choose more than 2, you'll get 2 out of the selected ones. All Buried Wonders enabled by default.\n\n[h1]Miscellaneous[/h1]\n[b]Advanced Signal Boosters[/b]: Signal Boosters will also increase the command radius of Asteroid Landers, Rockets, RC Commanders (including unique ones) and the Elevator by 15, instead of just Drone Hubs and Extenders.\n\n[b](Optional, Disabled by Default) Anti Freeze Protection[/b]: I found that sometimes the Elevator \"loses\" some colonists, who will search for a Dome non-stop until they freeze the game; when this option is enabled, the game will track those colonists and kill them. It might not solve all game freezes, but it's a start.\n\nThanks to Kurzgesagt's Video on Asteroid Mining ( https://www.youtube.com/watch?v=y8XvQNt26KI ) for some of these ideas.\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.jpg",
	'last_changes', "First version.",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "Tremualin_Library",
			'title', "Tremualin's Library",
			'version_major', 1,
			'version_minor', 10,
		}),
	},
	'id', "Tremualin_AdvancedBedAndBreakfast",
	'steam_id', "2801530978",
	'pops_desktop_uuid', "d4092621-5b29-49c5-9294-304b410e162d",
	'pops_any_uuid', "1ccad525-2dab-4727-b317-3fa319da4773",
	'author', "Tremualin",
	'version_major', 1,
	'version_minor', 1,
	'version', 27,
	'lua_revision', 1009413,
	'saved_with_revision', 1011140,
	'code', {
		"Code/Asteroids.lua",
		"Code/Miscellaneous.lua",
		"Code/Underground.lua",
	},
	'has_options', true,
	'saved', 1651297002,
	'screenshot1', "ModOptions.jpg",
	'screenshot2', "ToMarsAndBack.jpg",
	'screenshot3', "SolarEnergyLanders.jpg",
	'screenshot4', "UpgradeStorage.jpg",
	'screenshot5', "RefabAll.jpg",
	'TagGameplay', true,
})