return PlaceObj('ModDef', {
    'title', "Advanced Terraforming",
    'id', "Tremualin_AdvancedTerraforming",
    'pops_desktop_uuid', "a1dc9b5f-4fd9-409c-99c4-1a3dfc3eda7d",
    'pops_any_uuid', "2d2a040a-197f-48d6-8ec4-200d01844f0b",
    'author', "Tremualin",
    'version', 8,
    'lua_revision', 1009413,
    'saved_with_revision', 1010838,
    'code', {
        "Code/Atmosphere.lua",
        "Code/Miscellaneous.lua",
        "Code/Disasters.lua",
        "Code/SpaceRaceIntegration.lua",
        "Code/Temperature.lua",
        "Code/Vegetation.lua",
        "Code/Water.lua",
    },
    'saved', 1650938202,
})
