return PlaceObj('ModDef', {
	'title', "Seasons of Mars (Difficulty Mod)",
	'description', "Seasons of Mars aims to fulfill 2 goals: \n[list]\n[*]If you have Green Planet; make Terraforming much more important in the early to mid game.\n[*]If you have Below and Beyond; make Underground colonization and Asteroid mining much more important in the early to mid game.\n[/list]\n\nYou have a choice to make: Terraform as fast as possible, move your domes into the Underground, or weather the Weather?\n\nSeasons represent actual Martian Seasons (although their duration in game is half of the duration in real life), with each Season having unique effects, most of which are no longer relevant after Terraforming. This is a difficulty mod.\n\nThe game begins on Spring, the moment you enable the mod for the first time.\n\n[b]Seasons[/b]\n[list]\n    [*]Summer (89 sols): Dust Storms appear 0.5% faster each sol\n    [*]Autumn (71 sols): Cold Waves are 2.5% longer each sol. Dust Storms slowly normalize\n    [*]Winter (77 sols): Cold Waves appear 0.5% faster each sol\n    [*]Spring (97 sols): Dust Storms are 2.5% longer each sol. Cold Waves slowly normalize\n[/list]\n\n[b]Notes[/b] \nI'm not sure if this works without Green Planet; let me know in the comments.\nI still don't have the Below and Beyond DLC; but this mod is dealing strictly with Green Planet code, so I think it should work fine.\nNone of the effects are actually based on Science. There isn't much information to go around on Martian Seasons.\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.jpg",
	'last_changes', "Initial version",
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "Tremualin_Library",
			'title', "Tremualin's Library",
		}),
	},
	'id', "Tremualin_Seasons_Of_Mars",
	'steam_id', "2599530116",
	'pops_desktop_uuid', "395c7ade-b619-4528-8ae1-5752cdd09d3b",
	'pops_any_uuid', "a8229293-1d25-41d5-b9da-9b5b0220fb34",
	'author', "Tremualin",
	'version_major', 1,
	'version', 12,
	'lua_revision', 1007000,
	'saved_with_revision', 1007783,
	'code', {
		"Code/Seasons.lua",
		"Code/Notifications.lua",
		"Code/UnitTests.lua",
	},
	'saved', 1631395177,
	'screenshot1', "Welcome.png",
	'screenshot2', "Seasons.png",
	'screenshot3', "Long.png",
	'TagGameplay', true,
})