return PlaceObj('ModDef', {
	'title', "Mental Health is Health",
	'description', "Colonists visit health facilities only if health is less than 70, or sanity is less than 30.\nThis mod makes colonists visit health facilities if sanity is less than 70; which they will do ONLY if there's nothing else for them to do first (like work, eat, or rest). \n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.jpg",
	'last_changes', "Initial version",
	'id', "Tremualin_MentalHealth_Is_Health",
	'steam_id', "2624935819",
	'pops_desktop_uuid', "caf2492d-5c59-4e7f-b3f2-cf06f94e9cc0",
	'pops_any_uuid', "18dd3401-888b-41b1-8738-e17164b0c65c",
	'author', "Tremualin",
	'version_major', 1,
	'version', 5,
	'lua_revision', 1007000,
	'saved_with_revision', 1008107,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1633897733,
	'TagGameplay', true,
})