return PlaceObj('ModDef', {
    'title', "Water (Terraforming) Rebalanced",
    'description', "Water is way too easy to improve; you can spam Moisture Vaporators without consequence, and you only need to build a handful of Lakes to get 100% Water thanks to all the planetary missions. This mods makes that process a little harder, while making Lakes more desirable. \n\n[list]\n[*] Moisture Vaporators now suck Water out of the Atmosphere (-0.01% to -0.02% depending on Water level). \n[*] Each sol, 2% of current Water level is lost into outer-space while Atmosphere is not at 100%\n[*] Artificial Lakes (when full and unfrozen) provide additional comfort (2, 5, 10 and 20 for Small Lakes, Lakes, Large Lakes, and Huge Lakes respectively) to Domes up to 20 hexes away from the Lake.\n[/list]\n\nThe Moisture Vaporator change should make Water Excavators and Water Reclamation Spires more desirable.\nComfort bonuses from Lakes stack; if you can surround your Domes with beautiful and precious Water.\nDon't forget to up the level of Atmosphere before you become too invested in Water.\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
    'image', "Preview.jpg",
    'last_changes', "Initial version",
    'dependencies', {
        PlaceObj('ModDependency', {
            'id', "Tremualin_Library",
            'title', "Tremualin's Library",
        }),
    },
    'id', "Tremualin_Water_Rebalanced",
    'steam_id', "2603077738",
    'pops_desktop_uuid', "3de82609-8d2d-4ee2-bec2-96bba98aa1ea",
    'pops_any_uuid', "8a7eaec6-c590-4982-81bb-2bf11a8d4ce0",
    'author', "Tremualin",
    'version_major', 1,
    'version', 9,
    'lua_revision', 1007000,
    'saved_with_revision', 1007874,
    'code', {
        "Code/LakeComfort.lua",
        "Code/WaterLoss.lua",
        "Code/MoistureVaporatorSucksWater.lua",
    },
    'saved', 1631758869,
    'screenshot1', "MoistureVaporator.jpg",
    'screenshot2', "LakeComfort.jpg",
    'screenshot3', "WaterLoss.jpg",
    'TagGameplay', true,
    'TagTerraforming', true,
})
