return PlaceObj('ModDef', {
    'title', "Trait Galore",
    'description', "Trait Galore adds several new traits to spice up your game:\n \n[table] [tr] [th]Name[/th] [th]Type[/th] [th]Incompatible[/th] [th]Effect[/th] [th]Frequency[/th] [/tr][tr] [td]Anxious[/td][td]Flaw[/td][td]Composed[/td][td]-2 sanity whenever unable to immediately satisfy an interest.[/td][td]Normal[/td][/tr][tr] [td]Argumentative[/td][td]Flaw[/td][td]Listener[/td][td]Both this an another argumentative colonist in the same residence will lose 5 sanity each day.[/td][td]Normal[/td][/tr][tr] [td]Depressed[/td][td]Flaw[/td][td]Renegade[/td][td]80% chance of losing daily interest. Morale is set to 0. Chance for suicide and new flaws (affected by Supportive Community) every day unless assigned to a Sanatorium. -Social[/td][td]Very low[/td][/tr][tr] [td]Mean[/td][td]Flaw[/td][td]Kind[/td][td]-5 sanity to another random colonist in the same residence[/td][td]Normal[/td][/tr][tr] [td]Paranoid[/td][td]Flaw[/td][td]Composed[/td][td]-3 sanity when moving to a new location in or out of the Dome[/td][td]Low[/td][/tr][tr] [td]Fickle[/td][td]Perk[/td][td]Religious[/td][td]Alternates between different interests until it can satisfy one or goes to sleep. [/td][td]Low[/td][/tr][tr] [td]Fixer[/td][td]Perk[/td][td]Idiot[/td][td]Reduces the maintenance of any building it visits by 5%.[/td][td]Low[/td][/tr][tr] [td]Kind[/td][td]Perk[/td][td]Mean[/td][td]A random colonist in the same residence gets +5 Sanity. [/td][td]Normal[/td][/tr][tr] [td]Mentor[/td][td]Perk[/td][td]Loner[/td][td]Coworkers gain +20 performance and a moderate chance of losing the Idiot flaw; unless the Mentor is also an Idiot.[/td][td]Low[/td][/tr][tr] [td]Thrifty[/td][td]Perk[/td][td]Lazy[/td][td]Reduces the amount of resources consumed by the workplace by 5%. If the building consumes no resources, then it will reduce the consumption of electricity instead.[/td][td]Low[/td][/tr][tr] [td]Brawler[/td][td]Quirk[/td][td]Composed[/td][td]Once a day, if healthy, this an another healthy non-child will both lose 10 health; then both colonists regain 5 sanity. [/td][td]Normal[/td][/tr][tr] [td]Cynical[/td][td]Quirk[/td][td]Enthusiast[/td][td]All sanity gains and losses are halved (stacks with Composed)[/td][td]Low[/td][/tr][tr] [td]Early Bird[/td][td]Quirk[/td][td]Night Owl[/td][td]Gains/loses 5 comfort when working the morning/night. Will try to switch jobs with someone in the Morning Shift.[/td][td]Low[/td][/tr][tr] [td]Listener[/td][td]Quirk[/td][td]Argumentative[/td][td]The colonist with the lowest sanity in the residence gets +10 sanity. But this colonist will lose 5 sanity.[/td][td]Normal[/td][/tr][tr] [td]Night Owl[/td][td]Quirk[/td][td]Early Bird[/td][td]Gains/loses 5 comfort when working the night/morning. Regains sanity lost from Night Shifts. Will try to switch jobs with someone on the Night Shift[/td][td]Low[/td][/tr][/table]\n\n[b]Clarifications [/b]\n[list]\n    [*]Fixer, Kind, Mentor and Thrifty can be learned in School, but not Fickle. \n    [*]Anxious, Depressed, and Paranoid can be gained via sanity breakdown, but not Argumentative or Mean.\n    [*]All flaws can be cured in the Sanatorium.\n    [*]Quirks cannot be learned in Schools, nor cured in the Sanatorium.\n    [*]Thrifty can reduce Electronic Factories Rare Metals consumption from 0.3 to 0.15 if all workers are Thrifty; the UI however will show 0.2 because it rounds up, but it's still 0.15. \n   [*]Thrifty also reduces consumption of Grocers, Diners, Electronic/Art Stores, and Workshops. \n   [*]Fixer colonists are great in the late game if you want to move everyone into Smart Residences. They're also great for Science Domes which cost a lot of Electronics, and for Blue Sun Corporation and Paradox Interactive, whose unique buildings consume Electronics. \n  [*]Early Birds and Night Owls gain +5 comfort no matter what if assigned to the right shift (which they will do automatically if possible). They won't switch Workplaces however.\n[/list]\n\n[h2] Mod Integration [/h2]\nIf you have my [url=https://steamcommunity.com/sharedfiles/filedetails/?id=2567194262]Crime and Vindication[/url] mod, all flaws in this mod can be gained as a result of Domestic Violence.\n\n(Implementation in progress) If you have my [url=https://steamcommunity.com/sharedfiles/filedetails/?id=2535835676]Seniors with Benefits[/url] mod, then Seniors will be able to remove the new Flaws. I'm still working on which removes which.",
    'image', "Preview.png",
    'last_changes', "Edited description",
    'dependencies', {
        PlaceObj('ModDependency', {
            'id', "Tremualin_Library",
            'title', "Tremualin's Library",
        }),
    },
    'id', "Tremualin_Trait_Galore",
    'steam_id', "2589740365",
    'pops_desktop_uuid', "a99c9ffd-2368-4e52-bb5b-609d16fe1037",
    'pops_any_uuid', "d69d4ba6-aec7-4677-8047-7c5addc99f12",
    'author', "Tremualin",
    'version_major', 1,
    'version', 66,
    'lua_revision', 233360,
    'saved_with_revision', 1001586,
    'code', {
        "Code/Anxious.lua",
        "Code/Common.lua",
        "Code/Cynical.lua",
        "Code/Depressed.lua",
        "Code/EarlyBird_NightOwl.lua",
        "Code/Fickle.lua",
        "Code/Fixer.lua",
        "Code/Mentor.lua",
        "Code/Paranoid.lua",
        "Code/Thrifty.lua",
    },
    'saved', 1630384143,
    'screenshot1', "Perks.png",
    'screenshot2', "Flaws.png",
    'screenshot3', "Quirks.png",
    'TagTraits', true,
})
