return PlaceObj('ModDef', {
	'title', "Improved Breakthroughs",
	'description', "The goal of this mod is to improve some under-powered breakthroughs.\nThe mod doesn't always modify the description of the breakthroughs.\nCannot always modify already researched breakthroughs; a restart is required\n\nAlien Imprints\nOriginal:Uncovers new Anomalies - Alien Artifacts - which provide a boost to all research when scanned (3% reduced cost for each scanned Alien Artifact anomaly, from 3 to 10)\nModified: Uncovers new Anomalies - Alien Artifacts - which provide a boost to all research when scanned (3% reduced cost for each scanned Alien Artifact anomaly, always 10)\nMotivation: no more save scumming to get more anomalies\n\nGood Vibrations\nOriginal: Domes restore Sanity (+5) to their inhabitants every Sol.\nModified: Domes restore Health (+2.5) and Sanity (+5) to their inhabitants every Sol.\nMotivation: to set it apart from Rapid Sleep\n\nHive Mind\nOriginal: Residents in the Arcology get a bonus to work performance based on the number of unique Perks and specializations of colonists living in the Arcology.\nModified: Residents in any Residence get a bonus to work performance based on the number of unique Perks and specializations, minus the unique number of Flaws, of colonists living in the Residence\nMotivation: to make it on par with the other performance boosting technologies.\n\nPlasma Rocket\nOriginal: Rocket travel time to and from Earth reduced by 50%\nModified: Rocket travel time to and from Earth reduced by 50% and fuel consumption is reduced by 20 (SpaceY Space Race rockets no longer require fuel if you have both Plasma Rockets and Advanced Martian Engines )\nMotivation: early-game boost. \n\nVocation-Oriented Society\nOriginal: Colonists gain 10 bonus work performance when all their stats are in the green.\nModified: Colonists gain 15 bonus work performance when all their stats are in the green.\nMotivation: to make it on par with the other performance boosting technologies.\n\nSpace Rehabilitation\nOriginal: Colonists have a 50% chance to lose a flaw on their journey to Mars.\nModified: Colonists have a 100% chance to lost a flaw on their journey to Mars.\nMotivation: to make it a little better. Still not good enough.\n\nSoylent Green\nOriginal: Colonists drop 1 food on the ground up to a sol after death\nModified: Colonists drop 4 food on the ground immediately after death, then 1 more up to a sol after death\nMotivation: to make it on par with other food breakthroughs. \nClarifications: the code that drops 1 food is buried deep within the code, so I chose to leave it there.\n\nSuperfungus\nOriginal: Adds an upgrade which increases food production by 50% and oxygen consumption by 100%\nModified: Adds an upgrade which increases food production by 100% and oxygen consumption by 50%\nMotivation: to make it less penalizing for something that's supposed to be a breakthrough\n\n[url=https://steamcommunity.com/sharedfiles/filedetails/?id=2588828764]Steam[/url]\n[url=https://mods.paradoxplaza.com/authors/Tremualin]Paradox[/url]\n[url=https://github.com/Tremualin/SurvivingMarsMods]Github[/url]",
	'image', "Preview.png",
	'last_changes', "Fixed a bug with invalid colonists dying and soylent green",
	'id', "Tremualin_ImprovedBreakthroughs",
	'steam_id', "2509389568",
	'pops_desktop_uuid', "51815d6d-c444-4cd6-9ad5-18ac11d26abf",
	'pops_any_uuid', "892a7a83-98f7-411b-8623-d6f5108556d2",
	'author', "Tremualin",
	'version_major', 1,
	'version_minor', 4,
	'version', 25,
	'lua_revision', 1009413,
	'saved_with_revision', 1010838,
	'code', {
		"Code/Script.lua",
	},
	'saved', 1644885926,
	'TagGameplay', true,
})